
steps:

  # Create a service account for the job, enable the necessary APIs, and set the IAM policies
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./deploy/scripts/enableAPISAndCreateUser.sh','${_SERVICE_ACCOUNT_NAME}','${PROJECT_ID}']

  # Create and set the repository deletion policy
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./deploy/scripts/createRepositoryAndPolicy.sh','${_RUN_REGION}','${_ARTIFACT_REPO_NAME}']

  # Adds alerts to build and cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./deploy/scripts/createAlerts.sh','${_RUN_NAME}','${_EMAIL_ADDRESS}']

  # Pull the latest image to leverage caching and speed up the build. If the image doesn't exist, it will just continue without caching.
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull $_RUN_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_RUN_NAME:latest || exit 0']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    #Selecting the alpine image, which is slimmer and runs with chromium. You can change it to slim if you want.
    args: ['build', '-t', '$_RUN_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_RUN_NAME:latest', '.', '--cache-from', '$_RUN_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_RUN_NAME:latest', '--build-arg', 'BUILDKIT_INLINE_CACHE=1']
    env:
      - "DOCKER_BUILDKIT=1"

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -L -o ds.tar.gz https://github.com/mintoolkit/mint/releases/download/1.41.7/dist_linux.tar.gz;
        tar -xvf ds.tar.gz;
        mv dist_linux/mint /usr/local/bin/;
        mv dist_linux/mint-sensor /usr/local/bin/;
        mint build \
          --include-workdir=true \
          --http-probe=false \
          --sensor-ipc-mode proxy \
          --sensor-ipc-endpoint $(docker network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' | cut -f1) \
          --tag ${_RUN_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_RUN_NAME}:latest \
          ${_RUN_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_RUN_NAME}:latest;

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_RUN_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_RUN_NAME:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_RUN_NAME'
      - '--image'
      - '$_RUN_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_RUN_NAME:latest'
      - '--region'
      - '$_RUN_REGION'
      - '--service-account'
      - '$_SERVICE_ACCOUNT_NAME@$PROJECT_ID.iam.gserviceaccount.com'
      - '--concurrency'
      - 'default'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '60s'
      - '--execution-environment'
      - 'gen2'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--gpu'
      - '0'
      - '--startup-probe'
      - 'timeoutSeconds=240,periodSeconds=240,failureThreshold=1,tcpSocket.port=8080'
      - '--liveness-probe'
      - 'httpGet.path=/health'
      - '--no-cpu-boost'
      - '--cpu-throttling'
      - '--no-allow-unauthenticated'
      - '--no-allow-unencrypted-build'
      - '--session-affinity'
      - '--use-http2'
      - '--set-env-vars'
      - 'BALANZ_PASSWORD=$_BALANZ_PASSWORD,BALANZ_USER=$_BALANZ_USER,PROJECT_ID=$PROJECT_ID,BALANZ_TIMEOUT_SECS=$_BALANZ_TIMEOUT_SECS'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '$_RUN_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/$_RUN_NAME:latest'

substitutions:
  # Replace with the desired deployment region (I recommend us-central1)
  _RUN_REGION: 'us-central1'
  # Replace with the desired Cloud Run Jobs name (job name may only start with a letter and contain up to 63 lowercase letters, numbers or hyphens)
  _RUN_NAME: 'mep-bot'
  # Replace with the desired Artifact Repository name (needs to be lowercase and contain only letters, numbers, and hyphens)
  _ARTIFACT_REPO_NAME: 'mep-bot'
  # Replace with the desired service account's email address (it's something like username@projectname-projectnumber.iam.gserviceaccount.com
  _SERVICE_ACCOUNT_NAME: 'mep-bot'

#     Uncomment the following substitutions block to finish setting up your job:
#    Replace with the desired email address to get notifications from the alerts
#  _EMAIL_ADDRESS: ''
