services:
  app:
    container_name: app
    build:
      no_cache: false
      context: .
      network: host
    ports:
      - "8080:8080"
    environment:
        - BALANZ_USER=${BALANZ_USER}
        - BALANZ_PASSWORD=${BALANZ_PASSWORD}
        - PROJECT_ID=${PROJECT_ID}
        - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_PATH}:/app/credentials.json:ro
